name: Release dev

on:
  workflow_dispatch:

env:
  COMPONENT_DIR: ha_wavin_sentio_connect

jobs:
  release_zip_file:
    name: Prepare release asset
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Create zip
        run: |
          cd custom_components/ha_wavin_sentio_connect
          zip ha_wavin_sentio_connect.zip -r ./
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./custom_components/ha_wavin_sentio_connect/ha_wavin_sentio_connect.zip
          asset_name: ha_wavin_sentio_connect.zip
          tag: ${{ github.ref }}
          overwrite: true
